### ISSUE TITLE
Undefined function or variable 'newline'.

### ISSUE THREAD

**Issue by dchristle** [Conclusio/matlab-epsclean#2]
When I run this in MATLAB R2015b, I get the following error:

>> epsclean('out.eps')
Undefined function or variable 'newline'.

Error in epsclean (line 169)
            currentBlockPrefix = [currentBlockPrefix line newline]; %#ok<AGROW>

The "newline" element appears quite often in the code, and I am unsure of why it doesn't work in my version. It seems like this should be the equivalent of '\n' in the concatenated string, and so sprintf('\n') should produce the correct string char's on linux/windows/mac (since they all convert \n to different chars). I branched a local copy of the repo into a "fix_newline" branch and just submitted a pull request.

**Comment by Conclusio** [comment]
Thank you for your comment and your pull request. The original code was only tested on Matlab R2016b. And the built-in identifier 'newline' was introduced in that version.

I created a fix in case 'newline' is not defined for older Matlab versions and keep 'newline' in all other cases. I'd like to keep the OS's original line break behavior just in case (i.e. "\r\n" typically with Windows and "\n" otherwise).
